#!/usr/bin/env python
# binomo_executor.py
"""Part 3: executes binary-option trades on Binomo (binomo.com) for signals
generated by the existing cTrader-based pipeline (analysis.py / scanner.py),
via Playwright browser automation — Binomo has no public trading API.

ARCHITECTURE: this is a SEPARATE, STANDALONE LOCAL PROCESS. It is NOT part
of app.py's Twisted reactor / Flask app, is NOT deployed to Fly.io, and is
NOT imported by any cloud-side module (api.py, telegram_ui.py, bot.py never
import this file — Playwright isn't even in requirements.txt, only in
requirements-executor.txt, specifically so importing this module can never
happen by accident in the cloud process and crash it).

Why local instead of Fly.io: a persistent logged-in browser session
benefits from a stable IP and machine fingerprint; running it on a
shared/rotating cloud IP is both a worse fit for Binomo's anti-automation
checks and a bigger detection/ban risk for your account. Run this on your
own machine, pointed at the cloud instance's signal stream.

CROSS-PROCESS CONTROL: since this runs separately from the Telegram bot,
/binomo_status, /binomo_on and /binomo_off (telegram_ui.py, cloud process)
don't touch any in-memory flag here directly — they read/write shared flags
in the database (db.get_binomo_runtime_state / set_binomo_runtime_enabled /
trip_binomo_kill_switch), which this process polls. Same DATABASE_URL must
be reachable from both sides.

SAFETY MODEL (see config.py):
  - BINOMO_EXECUTOR_ENABLED=false by default (local .env). Nothing runs
    without this AND the DB-side runtime_enabled flag AND no tripped kill
    switch — see is_active().
  - BINOMO_ACCOUNT_MODE (demo|live) has NO remote/Telegram toggle anywhere.
    Switching to live is a manual local .env edit only.
  - BINOMO_STAKE_PERCENT is a fixed % of balance. There is no martingale/
    progression anywhere in this file, on purpose — do not add one.
  - Kill switches: BINOMO_MAX_TRADES_PER_DAY, BINOMO_MAX_CONSECUTIVE_LOSSES,
    BINOMO_MAX_DAILY_LOSS_PERCENT. Any of these trips a DB-persisted flag
    that stops new trades until an admin explicitly runs /binomo_on.

SELECTORS — verified 2026-08-09 against the live Binomo trading terminal
(Angular app) via a logged-in session, read-only DOM inspection only (no
amount/direction/confirm clicks were ever made during verification). Most
selectors use Binomo's own stable `id="qa_*"` QA hooks. Two known gaps
remain, both documented at their point of use instead of being guessed:
  - `asset_price_display` does not exist — Binomo renders the live price
    only inside a `<canvas>` chart, with no DOM/SVG/aria text node anywhere
    on the page. `_read_binomo_price()` always returns None until this is
    solved a different way (e.g. intercepting Binomo's price WebSocket).
  - `login_email_input`/`login_password_input`/`login_submit_button` are
    still unverified best-effort guesses (the login page 404s/redirects
    while already logged in, so it couldn't be inspected without logging
    the account out). This only affects the optional autofill convenience
    in `--login`; on failure it already logs a warning and lets you fill
    the form yourself, so it fails safe either way.
Nothing here guesses or falls back to a structural selector if the intended
one is missing — see _safe_find().
"""
import argparse
import csv
import json
import logging
import queue
import threading
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import requests

import config
import db
import signal_tracking
from notifier import notify_admin

logger = logging.getLogger("binomo_executor")

BINOMO_BASE_URL = "https://binomo.com"
BINOMO_TRADE_URL = "https://binomo.com/trading"

SCREENSHOT_DIR = Path("logs") / "binomo_screenshots"
CORRELATION_LOG_PATH = Path("logs") / "binomo_correlation_check.csv"
CORRELATION_LOG_FIELDS = [
    "logged_at", "pair", "binomo_asset", "verdict", "horizon_seconds",
    "ctrader_entry_price", "ctrader_exit_price", "ctrader_direction",
    "binomo_entry_price", "binomo_exit_price", "binomo_direction", "match",
]

# ----------------------------------------------------------------------
# Verified 2026-08-09 against the live terminal. See module docstring for
# the two known gaps (asset_price_display, login_* autofill).
# ----------------------------------------------------------------------
SELECTORS = {
    "login_email_input": "input[name='email']",  # unverified, see docstring
    "login_password_input": "input[name='password']",  # unverified, see docstring
    "login_submit_button": "button[type='submit']",  # unverified, see docstring
    "login_indicator": "#qa_trading_balance",  # presence == logged in
    "balance_amount": "#qa_trading_balance",
    "asset_picker_open_button": "#assets-list",
    "asset_search_input": "way-input-search input[type='text']",
    "asset_row": "div.asset-row",  # exact-match the name inside .name-text p — see place_binary_trade
    "asset_row_name": ".name-text p",
    "asset_price_display": None,  # does not exist — canvas-rendered, see module docstring
    "amount_control": "way-input-controls[type='currency']",
    "amount_input": "way-input-controls[type='currency'] input",
    "time_control": "#qa_trading_dealTimeInput",
    "time_input": "#qa_trading_dealTimeInput input",
    # DOM order confirmed live (minus at smaller x, plus at larger x); the
    # earlier icon-href :has() selector didn't match live (see git history)
    # so this uses position instead — still not a guess, just a different
    # empirically-confirmed anchor.
    "time_minus_button": "#qa_trading_dealTimeInput button >> nth=0",
    "time_plus_button": "#qa_trading_dealTimeInput button >> nth=1",
    "up_button": "#qa_trading_dealUpButton",
    "down_button": "#qa_trading_dealDownButton",
    "trade_confirmation_toast": "way-toast, .toast",  # best-effort; absence is not treated as failure, see place_binary_trade
    "trade_history_tab": "#qa_historyButton",
    "trade_history_standard_tab_button": "#qa_trading_tradeHistoryStandardButton",
    "trade_history_list": "#qa_trading_tradeHistoryStandardTab",
    "trade_history_row": "#qa_trading_tradeHistoryStandardTab div",  # row-level markup unverified — no trade existed yet to inspect; scoped :has-text() fallback, see read_trade_result
}

_DEFAULT_FIND_TIMEOUT_MS = 8000
_MAX_TIME_STEPPER_CLICKS = 60


# ----------------------------------------------------------------------
# Runtime state (mirrors autotrader.py's is_active()/enable()/disable()
# pattern, but backed by the shared DB instead of an in-memory flag, since
# /binomo_on and /binomo_off run in a different process).
# ----------------------------------------------------------------------

_local_kill_switch_cache = False


def is_active() -> bool:
    if not config.BINOMO_EXECUTOR_ENABLED:
        return False

    state = db.get_binomo_runtime_state()
    global _local_kill_switch_cache
    _local_kill_switch_cache = state["kill_switch_tripped"]
    return state["runtime_enabled"] and not state["kill_switch_tripped"]


def _trip_kill_switch(reason: str) -> None:
    if db.trip_binomo_kill_switch(reason):
        logger.critical("BINOMO KILL SWITCH: %s", reason)
        notify_admin(
            f"🛑 <b>BINOMO KILL SWITCH</b>\n{reason}\n"
            "Виконавця зупинено. Перевір рахунок вручну, тоді /binomo_on.",
            parse_mode="HTML",
        )


# ----------------------------------------------------------------------
# Asset map
# ----------------------------------------------------------------------


def load_asset_map() -> dict[str, dict]:
    path = Path(config.BINOMO_ASSET_MAP_PATH)
    if not path.is_absolute():
        path = config.BASE_DIR / path

    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        logger.exception("Could not load Binomo asset map from %s", path)
        return {}

    assets = data.get("assets") or {}
    if not data.get("_meta", {}).get("verified"):
        logger.warning(
            "Binomo asset map (%s) is marked unverified — trades will only be "
            "placed for pairs whose Binomo name has been manually confirmed. "
            "See _meta.how_to_verify in the file.",
            path,
        )
    return assets


def _resolve_binomo_asset_name(entry: dict) -> Optional[str]:
    """Binomo lists most forex pairs under a plain name on weekdays and
    switches to a separate '(OTC)' name (a different, synthetic price feed —
    see the correlation-check warning in this module's docstring) on
    weekends. Crypto pairs only ever exist under their OTC name. Picks by
    UTC weekday rather than guessing from whichever name happens to be
    present, since both names can be non-null at once."""
    is_weekend = datetime.now(timezone.utc).weekday() >= 5
    if is_weekend:
        return entry.get("otc_name") or entry.get("binomo_name")
    return entry.get("binomo_name") or entry.get("otc_name")


# ----------------------------------------------------------------------
# Playwright session
# ----------------------------------------------------------------------


def _storage_state_path() -> Path:
    path = Path(config.BINOMO_STORAGE_STATE_PATH)
    return path if path.is_absolute() else config.BASE_DIR / path


def login_and_save_session() -> None:
    """One-time (or as-needed) login helper: opens a VISIBLE browser and, if
    BINOMO_EMAIL/BINOMO_PASSWORD are set, pre-fills the login form as a
    convenience — it never clicks submit and never touches a CAPTCHA/2FA
    field; you always complete and confirm the login yourself. Saves the
    session to BINOMO_STORAGE_STATE_PATH once you confirm you're in. Run
    with:
        python binomo_executor.py --login
    """
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()
        page = context.new_page()
        page.goto(BINOMO_BASE_URL)

        if config.BINOMO_EMAIL and config.BINOMO_PASSWORD:
            try:
                page.wait_for_selector(SELECTORS["login_email_input"], timeout=_DEFAULT_FIND_TIMEOUT_MS)
                page.fill(SELECTORS["login_email_input"], config.BINOMO_EMAIL)
                page.fill(SELECTORS["login_password_input"], config.BINOMO_PASSWORD)
                print("Pre-filled email/password from .env — review, solve any CAPTCHA, then submit yourself.")
            except Exception:
                logger.warning(
                    "Could not pre-fill the login form (selector may need updating) — fill it in manually.",
                    exc_info=True,
                )

        print(
            "\nA browser window has opened. Log into your Binomo account "
            "yourself (solve any CAPTCHA/2FA yourself — this tool never "
            "attempts that, and never clicks the submit button for you). "
            "Once you're logged in and can see your balance, come back "
            "here and press Enter.\n"
        )
        input("Press Enter once logged in... ")

        state_path = _storage_state_path()
        state_path.parent.mkdir(parents=True, exist_ok=True)
        context.storage_state(path=str(state_path))
        print(f"Session saved to {state_path}. You can close the browser now.")
        browser.close()


def _launch_session(playwright, *, headless: bool):
    state_path = _storage_state_path()
    if not state_path.exists():
        raise RuntimeError(
            f"No saved Binomo session at {state_path}. Run "
            "`python binomo_executor.py --login` first."
        )

    browser = playwright.chromium.launch(headless=headless)
    context = browser.new_context(storage_state=str(state_path))
    page = context.new_page()
    page.goto(BINOMO_TRADE_URL)
    return browser, context, page


def _is_logged_in(page) -> bool:
    try:
        page.wait_for_selector(SELECTORS["login_indicator"], timeout=_DEFAULT_FIND_TIMEOUT_MS)
        return True
    except Exception:
        return False


# ----------------------------------------------------------------------
# Safe DOM interaction — never guesses an alternate selector. On timeout:
# screenshot, log, return None. Callers must treat None as "stop, don't
# trade", per the task's own explicit rule.
# ----------------------------------------------------------------------


def _screenshot(page, tag: str) -> Optional[str]:
    try:
        SCREENSHOT_DIR.mkdir(parents=True, exist_ok=True)
        ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
        path = SCREENSHOT_DIR / f"{ts}_{tag}.png"
        page.screenshot(path=str(path))
        return str(path)
    except Exception:
        logger.exception("Could not save audit screenshot for %s", tag)
        return None


def _safe_find(page, selector: str, *, description: str, timeout_ms: int = _DEFAULT_FIND_TIMEOUT_MS):
    try:
        return page.wait_for_selector(selector, timeout=timeout_ms)
    except Exception:
        shot = _screenshot(page, f"missing_{description}")
        logger.error(
            "Binomo executor: element not found for '%s' (selector=%r). "
            "Not guessing an alternative — stopping this action. Screenshot: %s",
            description, selector, shot,
        )
        notify_admin(
            f"⚠️ Binomo executor: елемент \"{description}\" не знайдено на сторінці. "
            "Потрібна ручна перевірка (можливо, змінився дизайн сайту). "
            f"Скріншот: {shot or 'не вдалося зберегти'}",
        )
        return None


# ----------------------------------------------------------------------
# Balance
# ----------------------------------------------------------------------


def _parse_numeric_text(text: str) -> Optional[float]:
    """Binomo displays numbers in Ukrainian/European locale - comma as the
    decimal separator, space as the thousands separator (e.g. balance shown
    as "350 712,00 ₴"). Just deleting the comma (as an earlier version of
    this did) silently produced a balance 100x too large, confirmed
    2026-08-09 - a real risk since balance directly feeds stake sizing.
    Spaces are already excluded by the digit/./, filter below."""
    try:
        cleaned = "".join(ch for ch in text if ch.isdigit() or ch in ".,")
        if "," in cleaned:
            cleaned = cleaned.replace(".", "").replace(",", ".")
        return float(cleaned) if cleaned else None
    except Exception:
        return None


def get_account_balance(page) -> Optional[float]:
    el = _safe_find(page, SELECTORS["balance_amount"], description="balance_amount")
    if el is None:
        return None

    try:
        return _parse_numeric_text(el.inner_text().strip())
    except Exception:
        logger.exception("Could not parse Binomo balance text")
        return None


# ----------------------------------------------------------------------
# Trade placement
# ----------------------------------------------------------------------


def _parse_hhmm(text: str) -> Optional[int]:
    try:
        h, m = text.strip().split(":")
        return int(h) * 60 + int(m)
    except Exception:
        return None


def _set_expiry_time(page, expiry_seconds: int) -> bool:
    """Binomo's expiry control (#qa_trading_dealTimeInput) is a readonly
    absolute clock-time field advanced only via +/- stepper buttons, not a
    duration dropdown. Reads the baseline value, then clicks '+' until the
    elapsed time — measured relative to that baseline, both read from
    Binomo's own displayed clock, so no wall-clock/timezone sync is needed —
    reaches the requested horizon. Self-correcting rather than assuming a
    fixed per-click step, since that step size was never confirmed live
    (verification stayed read-only and never clicked this control)."""
    time_input = _safe_find(page, SELECTORS["time_input"], description="time_input")
    if time_input is None:
        return False

    baseline_minutes = _parse_hhmm(time_input.input_value())
    if baseline_minutes is None:
        logger.error("Binomo executor: could not parse deal time '%s'", time_input.input_value())
        return False

    target_minutes_elapsed = max(1, round(expiry_seconds / 60))

    plus_button = _safe_find(page, SELECTORS["time_plus_button"], description="time_plus_button")
    if plus_button is None:
        return False

    for _ in range(_MAX_TIME_STEPPER_CLICKS):
        current_minutes = _parse_hhmm(time_input.input_value())
        if current_minutes is None:
            break
        elapsed = (current_minutes - baseline_minutes) % (24 * 60)
        if elapsed >= target_minutes_elapsed:
            return True
        plus_button.click()

    logger.error(
        "Binomo executor: could not reach target expiry (%ss) after %d stepper clicks — "
        "not guessing further, stopping.", expiry_seconds, _MAX_TIME_STEPPER_CLICKS,
    )
    return False


def _fill_amount(page, amount: float) -> bool:
    """A plain .fill() on this Angular currency-masked input was confirmed
    live to silently mangle the value (typed "40.00", field showed "₴40.4")
    instead of erroring. Switching to character-by-character typing
    surfaced a second finding: this field doesn't accept a decimal point at
    all — it silently drops "." and concatenates the remaining digits (typed
    "40.00" -> field showed "₴4000"), confirmed 2026-08-09 on this UAH demo
    account. Rounds to the nearest whole currency unit and types digits
    only, then reads the field back and refuses to proceed on any mismatch
    rather than trusting the input silently worked."""
    amount_input = _safe_find(page, SELECTORS["amount_input"], description="amount_input")
    if amount_input is None:
        return False

    target = int(round(amount))
    amount_input.click()
    amount_input.press("Control+A")
    amount_input.press("Backspace")
    amount_input.type(str(target))

    actual = _parse_numeric_text(amount_input.input_value())
    if actual is None or abs(actual - target) > 0.5:
        shot = _screenshot(page, "amount_mismatch")
        logger.error(
            "Binomo executor: amount field shows %r after typing %d (requested %.2f) — "
            "mismatch, not trusting it and aborting. Screenshot: %s",
            amount_input.input_value(), target, amount, shot,
        )
        notify_admin(
            f"⚠️ Binomo executor: поле суми показує {amount_input.input_value()!r} "
            f"замість {target} — угоду скасовано, потрібна ручна перевірка."
        )
        return False

    return True


def place_binary_trade(page, asset: str, direction: str, amount: float, expiry_seconds: int) -> dict:
    """direction: 'up' | 'down'. Returns {"success": bool, "error": str|None}.
    Every real click on amount/direction is preceded by an audit screenshot,
    per the task's audit-trail requirement."""
    if direction not in ("up", "down"):
        return {"success": False, "error": f"invalid direction: {direction}"}

    picker_button = _safe_find(page, SELECTORS["asset_picker_open_button"], description="asset_picker_open_button")
    if picker_button is None:
        return {"success": False, "error": "asset_picker_open_button not found"}
    picker_button.click()

    search_input = _safe_find(page, SELECTORS["asset_search_input"], description="asset_search_input")
    if search_input is None:
        return {"success": False, "error": "asset_search_input not found"}
    search_input.fill(asset)

    row_selector = f"{SELECTORS['asset_row']}:has({SELECTORS['asset_row_name']}:text-is('{asset}'))"
    asset_row = _safe_find(page, row_selector, description="asset_row")
    if asset_row is None:
        return {"success": False, "error": f"asset row not found for {asset!r}"}
    asset_row.click()

    if not _fill_amount(page, amount):
        return {"success": False, "error": "could not set amount"}

    _screenshot(page, f"before_amount_{asset}_{direction}")

    if not _set_expiry_time(page, expiry_seconds):
        return {"success": False, "error": "could not set expiry time"}

    direction_selector = SELECTORS["up_button"] if direction == "up" else SELECTORS["down_button"]
    direction_button = _safe_find(page, direction_selector, description=f"{direction}_button")
    if direction_button is None:
        return {"success": False, "error": f"{direction}_button not found"}

    _screenshot(page, f"before_click_{asset}_{direction}")
    direction_button.click()

    confirmation = _safe_find(
        page, SELECTORS["trade_confirmation_toast"], description="trade_confirmation_toast", timeout_ms=5000
    )
    if confirmation is None:
        # Not necessarily a failure — some UIs skip a toast — but we can't
        # positively confirm the trade went through either. Log loudly.
        logger.warning("Binomo executor: no confirmation toast seen after clicking %s on %s", direction, asset)

    return {"success": True, "error": None}


def read_trade_result(page, asset: str, entered_after: datetime) -> dict:
    """Reads the most recent resolved trade for `asset` opened at/after
    `entered_after` from Binomo's trade history. Returns
    {"result": "win"|"loss"|"unknown", "payout_amount": float|None}."""
    history_tab = _safe_find(page, SELECTORS["trade_history_tab"], description="trade_history_tab")
    if history_tab is None:
        return {"result": "unknown", "payout_amount": None}
    history_tab.click()

    try:
        page.click(SELECTORS["trade_history_standard_tab_button"], timeout=3000)
    except Exception:
        pass  # may already be the selected sub-tab

    row = _safe_find(page, f"{SELECTORS['trade_history_row']}:has-text('{asset}')", description="trade_history_row")
    if row is None:
        return {"result": "unknown", "payout_amount": None}

    try:
        text = row.inner_text().lower()
        if "win" in text or "виграш" in text:
            outcome = "win"
        elif "loss" in text or "програш" in text:
            outcome = "loss"
        else:
            outcome = "unknown"

        digits = "".join(ch for ch in text if ch.isdigit() or ch in ".,-").strip()
        payout = float(digits.replace(",", "")) if digits else None
        return {"result": outcome, "payout_amount": payout}
    except Exception:
        logger.exception("Could not parse Binomo trade history row for %s", asset)
        return {"result": "unknown", "payout_amount": None}


# ----------------------------------------------------------------------
# Risk checks
# ----------------------------------------------------------------------


def _check_risk_limits(balance: float) -> Optional[str]:
    """Returns a reason string if a trade should be blocked, else None.
    Trips the kill switch itself when a hard limit (consecutive losses /
    daily loss) is breached."""
    trades_today = db.count_binomo_trades_today(config.BINOMO_ACCOUNT_MODE)
    if trades_today >= config.BINOMO_MAX_TRADES_PER_DAY:
        return f"MAX_TRADES_PER_DAY reached ({trades_today}/{config.BINOMO_MAX_TRADES_PER_DAY})"

    losses = db.get_consecutive_binomo_losses(config.BINOMO_ACCOUNT_MODE)
    if losses >= config.BINOMO_MAX_CONSECUTIVE_LOSSES:
        _trip_kill_switch(
            f"{losses} збитків поспіль (ліміт {config.BINOMO_MAX_CONSECUTIVE_LOSSES})"
        )
        return "MAX_CONSECUTIVE_LOSSES kill switch tripped"

    daily_pnl = db.get_daily_binomo_pnl(config.BINOMO_ACCOUNT_MODE)
    max_daily_loss = balance * (config.BINOMO_MAX_DAILY_LOSS_PERCENT / 100.0)
    if daily_pnl <= -max_daily_loss:
        _trip_kill_switch(
            f"Денний PnL {daily_pnl:.2f} перевищив ліміт -{max_daily_loss:.2f} "
            f"({config.BINOMO_MAX_DAILY_LOSS_PERCENT}% балансу)"
        )
        return "MAX_DAILY_LOSS_PERCENT kill switch tripped"

    return None


# ----------------------------------------------------------------------
# Signal stream (background thread — only ever pushes into a queue; all
# Playwright calls stay on the main thread, since a Page isn't safe to
# drive from multiple threads at once)
# ----------------------------------------------------------------------


def _signal_stream_url() -> str:
    base = config.get_public_base_url()
    token = config.get_admin_access_token()
    if not token:
        raise RuntimeError(
            "ADMIN_ACCESS_TOKEN is not set — the local executor needs it to "
            "read /api/signal-stream from the cloud instance."
        )
    return f"{base}/api/signal-stream?admin_token={token}"


_STREAM_RECONNECT_BASE_SECONDS = 5
_STREAM_RECONNECT_MAX_SECONDS = 60


def _stream_signals(out_queue: "queue.Queue[dict]", stop_event: threading.Event) -> None:
    """SSE connections drop regularly (ChunkedEncodingError, idle proxy
    timeouts, etc.) - that's normal, not a bug, as long as this reconnects.
    Exponential backoff (capped) so a sustained cloud-side outage doesn't
    hammer it every few seconds; backoff resets once an event actually
    arrives, so a brief blip doesn't leave a stale long delay in place.
    Treats the generator ending WITHOUT an exception the same as a
    disconnect and still backs off before retrying - some sseclient-py
    versions can end the loop silently on a dropped connection instead of
    raising, and a stream that's supposed to be infinite ending "cleanly"
    is itself a disconnect, not a normal completion."""
    import sseclient

    url = _signal_stream_url()
    backoff = _STREAM_RECONNECT_BASE_SECONDS

    while not stop_event.is_set():
        connected_at = time.monotonic()
        response = None
        try:
            response = requests.get(url, stream=True, timeout=(10, None))
            client = sseclient.SSEClient(response)
            for event in client.events():
                if stop_event.is_set():
                    break
                if not event.data:
                    continue
                try:
                    payload = json.loads(event.data)
                except ValueError:
                    continue
                if payload.get("_ping"):
                    continue
                out_queue.put(payload)
                backoff = _STREAM_RECONNECT_BASE_SECONDS
        except Exception:
            logger.warning(
                "Binomo executor: signal stream disconnected after %.0fs",
                time.monotonic() - connected_at, exc_info=True,
            )
        finally:
            if response is not None:
                try:
                    response.close()
                except Exception:
                    pass

        if stop_event.is_set():
            break

        logger.info("Binomo executor: signal stream reconnecting in %ss", backoff)
        if stop_event.wait(backoff):
            break
        backoff = min(backoff * 2, _STREAM_RECONNECT_MAX_SECONDS)


# ----------------------------------------------------------------------
# Main loop
# ----------------------------------------------------------------------


def _handle_signal(page, asset_map: dict, signal: dict) -> None:
    if not is_active():
        return

    verdict = str(signal.get("verdict_text") or "").upper()
    if verdict not in ("BUY", "SELL"):
        return

    pair = str(signal.get("pair") or "").upper()
    entry = asset_map.get(pair)
    asset_name = entry and _resolve_binomo_asset_name(entry)
    if not asset_name:
        logger.debug("Binomo executor: %s not tradable on Binomo right now, skipping", pair)
        return

    balance = get_account_balance(page)
    if not balance or balance <= 0:
        logger.warning("Binomo executor: could not read balance, skipping %s", pair)
        return

    block_reason = _check_risk_limits(balance)
    if block_reason:
        logger.info("Binomo executor: blocked %s (%s)", pair, block_reason)
        return

    direction = "up" if verdict == "BUY" else "down"
    expiry_seconds = signal_tracking.compute_horizon_seconds(signal.get("timeframe"))
    amount = round(balance * (config.BINOMO_STAKE_PERCENT / 100.0), 2)

    trade_id = db.create_binomo_trade(
        asset=asset_name,
        pair=pair,
        direction=direction,
        amount=amount,
        expiry_seconds=expiry_seconds,
        account_mode=config.BINOMO_ACCOUNT_MODE,
    )
    if not trade_id:
        logger.error("Binomo executor: could not log pending trade for %s, aborting placement", pair)
        return

    logger.info(
        "BINOMO: placing #%s %s %s amount=%.2f expiry=%ss (mode=%s)",
        trade_id, asset_name, direction, amount, expiry_seconds, config.BINOMO_ACCOUNT_MODE,
    )
    result = place_binary_trade(page, asset_name, direction, amount, expiry_seconds)

    if not result["success"]:
        db.mark_binomo_trade_error(trade_id, result["error"] or "unknown error")
        notify_admin(f"❌ Binomo #{trade_id} {asset_name} {direction}: {result['error']}")
        return

    notify_admin(
        f"📥 Binomo #{trade_id} {asset_name} {direction.upper()}\n"
        f"Сума: {amount:.2f} · Експірація: {expiry_seconds}с · Режим: {config.BINOMO_ACCOUNT_MODE}"
    )


def _resolve_due_trades(page) -> None:
    now = datetime.now(timezone.utc).replace(tzinfo=None)

    for trade in db.get_pending_binomo_trades(config.BINOMO_ACCOUNT_MODE):
        entry_ts = trade["entry_ts"]
        if not isinstance(entry_ts, datetime):
            continue
        due_at = entry_ts.timestamp() + trade["expiry_seconds"]
        if now.timestamp() < due_at:
            continue

        outcome = read_trade_result(page, trade["asset"], entry_ts)
        if outcome["result"] == "unknown":
            continue  # try again next pass; don't guess

        if db.resolve_binomo_trade(trade["id"], result=outcome["result"], payout_amount=outcome["payout_amount"]):
            payout = outcome["payout_amount"]
            logger.info(
                "BINOMO: #%s %s %s -> %s (payout=%s)",
                trade["id"], trade["asset"], trade["direction"], outcome["result"], payout,
            )
            notify_admin(
                f"📤 Binomo #{trade['id']} {trade['asset']} {trade['direction'].upper()} "
                f"→ {outcome['result'].upper()}"
                + (f" ({payout:+.2f})" if isinstance(payout, (int, float)) else "")
            )


def run(*, headless: bool = None) -> None:
    from playwright.sync_api import sync_playwright

    if not config.BINOMO_EXECUTOR_ENABLED:
        logger.warning("BINOMO_EXECUTOR_ENABLED=false — exiting immediately. Set it in your local .env to run.")
        return

    asset_map = load_asset_map()
    if not asset_map:
        logger.error("Binomo asset map is empty — nothing to trade. Check %s", config.BINOMO_ASSET_MAP_PATH)
        return

    signal_queue: "queue.Queue[dict]" = queue.Queue()
    stop_event = threading.Event()
    stream_thread = threading.Thread(
        target=_stream_signals, args=(signal_queue, stop_event), name="binomo-signal-stream", daemon=True
    )
    stream_thread.start()

    with sync_playwright() as p:
        browser, context, page = _launch_session(p, headless=config.BINOMO_HEADLESS if headless is None else headless)

        if not _is_logged_in(page):
            notify_admin(
                "🛑 Binomo executor: сесія недійсна/протермінована. "
                "Запусти `python binomo_executor.py --login` вручну на ноуті."
            )
            logger.critical("Binomo executor: not logged in (stale storage_state?). Exiting.")
            browser.close()
            stop_event.set()
            return

        logger.info("Binomo executor started (mode=%s, enabled=%s)", config.BINOMO_ACCOUNT_MODE, config.BINOMO_EXECUTOR_ENABLED)

        try:
            while True:
                try:
                    signal = signal_queue.get(timeout=2.0)
                    _handle_signal(page, asset_map, signal)
                except queue.Empty:
                    pass

                _resolve_due_trades(page)
        except KeyboardInterrupt:
            logger.info("Binomo executor stopping (KeyboardInterrupt).")
        finally:
            stop_event.set()
            browser.close()


# ----------------------------------------------------------------------
# --correlation-check: does the cTrader feed's direction actually match
# Binomo's own feed for the same asset/horizon? Places NO trades and
# ignores risk limits/kill switch entirely — pure observation, logged to
# a CSV. Deliberately independent of Part 1's SignalOutcome table (which
# only ever tracks cTrader-side movement) per the task's own instruction
# not to conflate the two.
# ----------------------------------------------------------------------


def _fetch_ctrader_price(pair: str) -> Optional[float]:
    base = config.get_public_base_url()
    token = config.get_admin_access_token()
    if not token:
        logger.error("Correlation-check: ADMIN_ACCESS_TOKEN not set, cannot fetch cTrader price")
        return None

    try:
        response = requests.get(
            f"{base}/api/live_price", params={"pairs": pair, "admin_token": token}, timeout=10
        )
        response.raise_for_status()
        data = response.json()
        entry = (data.get("prices") or {}).get(pair)
        return entry.get("mid") if entry else None
    except Exception:
        logger.exception("Correlation-check: failed to fetch cTrader price for %s", pair)
        return None


_price_display_warning_logged = False


def _read_binomo_price(page, asset_name: str) -> Optional[float]:
    if SELECTORS["asset_price_display"] is None:
        global _price_display_warning_logged
        if not _price_display_warning_logged:
            logger.warning(
                "Binomo executor: asset_price_display has no selector — Binomo renders "
                "its live price only inside a <canvas> chart, with no accessible DOM/SVG "
                "text anywhere on the page (confirmed 2026-08-09 via live DOM inspection). "
                "--correlation-check cannot read Binomo-side prices until this is solved "
                "a different way (e.g. intercepting Binomo's price WebSocket in Playwright). "
                "Binomo-side entries will log as 'unknown' until then — eyeball the chart "
                "yourself during early correlation-check runs."
            )
            _price_display_warning_logged = True
        return None

    el = _safe_find(page, SELECTORS["asset_price_display"], description="asset_price_display")
    if el is None:
        return None
    try:
        return _parse_numeric_text(el.inner_text().strip())
    except Exception:
        logger.exception("Could not parse Binomo price text for %s", asset_name)
        return None


def _classify_or_unknown(entry: Optional[float], exit_: Optional[float]) -> str:
    if not isinstance(entry, (int, float)) or not isinstance(exit_, (int, float)):
        return "unknown"
    return signal_tracking._classify_move(entry, exit_)


def _append_correlation_log(row: dict) -> None:
    CORRELATION_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    is_new = not CORRELATION_LOG_PATH.exists()
    with open(CORRELATION_LOG_PATH, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CORRELATION_LOG_FIELDS)
        if is_new:
            writer.writeheader()
        writer.writerow(row)


def _start_correlation_entry(page, asset_map: dict, signal: dict, pending: list, lock: threading.Lock) -> None:
    verdict = str(signal.get("verdict_text") or "").upper()
    if verdict not in ("BUY", "SELL"):
        return

    pair = str(signal.get("pair") or "").upper()
    entry = asset_map.get(pair)
    asset_name = entry and _resolve_binomo_asset_name(entry)
    if not asset_name:
        return

    ctrader_entry_price = signal.get("price")
    if not isinstance(ctrader_entry_price, (int, float)):
        return

    binomo_entry_price = _read_binomo_price(page, asset_name)
    horizon_seconds = signal_tracking.compute_horizon_seconds(signal.get("timeframe"))

    record = {
        "pair": pair,
        "binomo_asset": asset_name,
        "verdict": verdict,
        "horizon_seconds": horizon_seconds,
        "ctrader_entry_price": ctrader_entry_price,
        "binomo_entry_price": binomo_entry_price,
        "due_at": time.time() + horizon_seconds,
    }
    with lock:
        pending.append(record)

    logger.info(
        "Correlation-check: tracking %s %s ctrader_entry=%s binomo_entry=%s (horizon=%ss)",
        pair, verdict, ctrader_entry_price, binomo_entry_price, horizon_seconds,
    )


def _resolve_due_correlation_entries(page, pending: list, lock: threading.Lock) -> None:
    now = time.time()
    with lock:
        due = [r for r in pending if r["due_at"] <= now]
        for r in due:
            pending.remove(r)

    for record in due:
        ctrader_exit_price = _fetch_ctrader_price(record["pair"])
        binomo_exit_price = _read_binomo_price(page, record["binomo_asset"])

        ctrader_direction = _classify_or_unknown(record["ctrader_entry_price"], ctrader_exit_price)
        binomo_direction = _classify_or_unknown(record["binomo_entry_price"], binomo_exit_price)
        match = ctrader_direction == binomo_direction and ctrader_direction != "unknown"

        _append_correlation_log(
            {
                "logged_at": datetime.now(timezone.utc).isoformat(),
                "pair": record["pair"],
                "binomo_asset": record["binomo_asset"],
                "verdict": record["verdict"],
                "horizon_seconds": record["horizon_seconds"],
                "ctrader_entry_price": record["ctrader_entry_price"],
                "ctrader_exit_price": ctrader_exit_price,
                "ctrader_direction": ctrader_direction,
                "binomo_entry_price": record["binomo_entry_price"],
                "binomo_exit_price": binomo_exit_price,
                "binomo_direction": binomo_direction,
                "match": match,
            }
        )
        logger.info(
            "Correlation-check RESULT: %s ctrader=%s binomo=%s match=%s",
            record["pair"], ctrader_direction, binomo_direction, match,
        )


def run_correlation_check(*, headless: bool = None) -> None:
    from playwright.sync_api import sync_playwright

    asset_map = load_asset_map()
    if not asset_map:
        logger.error("Binomo asset map is empty — nothing to check. See %s", config.BINOMO_ASSET_MAP_PATH)
        return

    pending: list = []
    lock = threading.Lock()

    signal_queue: "queue.Queue[dict]" = queue.Queue()
    stop_event = threading.Event()
    stream_thread = threading.Thread(
        target=_stream_signals, args=(signal_queue, stop_event), name="binomo-correlation-stream", daemon=True
    )
    stream_thread.start()

    with sync_playwright() as p:
        browser, context, page = _launch_session(p, headless=config.BINOMO_HEADLESS if headless is None else headless)

        if not _is_logged_in(page):
            logger.critical("Correlation-check: not logged in. Run `python binomo_executor.py --login` first.")
            browser.close()
            stop_event.set()
            return

        logger.info(
            "Correlation-check started — NO trades will be placed, only price "
            "comparisons logged to %s. Leave this running for a few days before "
            "trusting these signals with real money.",
            CORRELATION_LOG_PATH,
        )

        try:
            while True:
                try:
                    signal = signal_queue.get(timeout=2.0)
                    _start_correlation_entry(page, asset_map, signal, pending, lock)
                except queue.Empty:
                    pass

                _resolve_due_correlation_entries(page, pending, lock)
        except KeyboardInterrupt:
            logger.info("Correlation-check stopping (KeyboardInterrupt).")
        finally:
            stop_event.set()
            browser.close()


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")

    parser = argparse.ArgumentParser(description="Binomo binary-option executor (local, Playwright-based).")
    parser.add_argument("--login", action="store_true", help="One-time/manual login helper; saves storage_state.json.")
    parser.add_argument("--run", action="store_true", help="Run the live executor loop (places real demo/live trades).")
    parser.add_argument(
        "--correlation-check", action="store_true",
        help="Log cTrader-vs-Binomo directional agreement only — places NO trades. Run this first.",
    )
    parser.add_argument("--headless", action="store_true", help="Force headless mode for --run/--correlation-check.")
    args = parser.parse_args()

    if args.login:
        login_and_save_session()
    elif args.correlation_check:
        run_correlation_check(headless=True if args.headless else None)
    elif args.run:
        run(headless=True if args.headless else None)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
