#!/usr/bin/env python
# binomo_executor.py
"""Part 3: executes binary-option trades on Binomo (binomo.com) for signals
generated by the existing cTrader-based pipeline (analysis.py / scanner.py),
via Playwright browser automation — Binomo has no public trading API.

ARCHITECTURE: this is a SEPARATE, STANDALONE LOCAL PROCESS. It is NOT part
of app.py's Twisted reactor / Flask app, is NOT deployed to Fly.io, and is
NOT imported by any cloud-side module (api.py, telegram_ui.py, bot.py never
import this file — Playwright isn't even in requirements.txt, only in
requirements-executor.txt, specifically so importing this module can never
happen by accident in the cloud process and crash it).

Why local instead of Fly.io: a persistent logged-in browser session
benefits from a stable IP and machine fingerprint; running it on a
shared/rotating cloud IP is both a worse fit for Binomo's anti-automation
checks and a bigger detection/ban risk for your account. Run this on your
own machine, pointed at the cloud instance's signal stream.

CROSS-PROCESS CONTROL: since this runs separately from the Telegram bot,
/binomo_status, /binomo_on and /binomo_off (telegram_ui.py, cloud process)
don't touch any in-memory flag here directly — they read/write shared flags
in the database (db.get_binomo_runtime_state / set_binomo_runtime_enabled /
trip_binomo_kill_switch), which this process polls. Same DATABASE_URL must
be reachable from both sides.

SAFETY MODEL (see config.py):
  - BINOMO_EXECUTOR_ENABLED=false by default (local .env). Nothing runs
    without this AND the DB-side runtime_enabled flag AND no tripped kill
    switch — see is_active().
  - BINOMO_ACCOUNT_MODE (demo|live) has NO remote/Telegram toggle anywhere.
    Switching to live is a manual local .env edit only.
  - BINOMO_STAKE_PERCENT is a fixed % of balance. There is no martingale/
    progression anywhere in this file, on purpose — do not add one.
  - Kill switches: BINOMO_MAX_TRADES_PER_DAY, BINOMO_MAX_CONSECUTIVE_LOSSES,
    BINOMO_MAX_DAILY_LOSS_PERCENT. Any of these trips a DB-persisted flag
    that stops new trades until an admin explicitly runs /binomo_on.

SELECTORS — READ THIS: every Binomo DOM selector below is a labeled
PLACEHOLDER (search for "VERIFY-SELECTOR"). I cannot log into your Binomo
account, so I cannot confirm the actual data-testid/aria-label/DOM
structure of the live trading terminal. Before running anything beyond
`--login`, log in yourself and replace each placeholder with the real
selector (prefer data-testid/aria-label over structural CSS, per the task's
own stability requirement). Nothing here guesses or falls back to a
structural selector if the intended one is missing — see _safe_find().
"""
import argparse
import json
import logging
import queue
import threading
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import requests

import config
import db
import signal_tracking
from notifier import notify_admin

logger = logging.getLogger("binomo_executor")

BINOMO_BASE_URL = "https://binomo.com"
BINOMO_TRADE_URL = "https://binomo.com/trading"

SCREENSHOT_DIR = Path("logs") / "binomo_screenshots"

# ----------------------------------------------------------------------
# VERIFY-SELECTOR: placeholders. Replace with real selectors from the live
# Binomo terminal DOM before trusting this against real trades.
# ----------------------------------------------------------------------
SELECTORS = {
    "login_email_input": "input[name='email']",
    "login_password_input": "input[name='password']",
    "login_submit_button": "button[type='submit']",
    "login_indicator": "[data-testid='balance-amount']",  # presence == logged in
    "balance_amount": "[data-testid='balance-amount']",
    "account_mode_switch": "[data-testid='account-mode-switch']",
    "asset_search_input": "[data-testid='asset-search-input']",
    "asset_option": "[data-testid='asset-option']",  # filter by text=asset name
    "amount_input": "[data-testid='trade-amount-input']",
    "expiry_selector": "[data-testid='trade-expiry-selector']",
    "expiry_option": "[data-testid='expiry-option']",  # filter by text/seconds
    "up_button": "[data-testid='trade-up-button']",
    "down_button": "[data-testid='trade-down-button']",
    "trade_confirmation_toast": "[data-testid='trade-confirmation-toast']",
    "trade_history_tab": "[data-testid='trade-history-tab']",
    "trade_history_row": "[data-testid='trade-history-row']",
}

_DEFAULT_FIND_TIMEOUT_MS = 8000


# ----------------------------------------------------------------------
# Runtime state (mirrors autotrader.py's is_active()/enable()/disable()
# pattern, but backed by the shared DB instead of an in-memory flag, since
# /binomo_on and /binomo_off run in a different process).
# ----------------------------------------------------------------------

_local_kill_switch_cache = False


def is_active() -> bool:
    if not config.BINOMO_EXECUTOR_ENABLED:
        return False

    state = db.get_binomo_runtime_state()
    global _local_kill_switch_cache
    _local_kill_switch_cache = state["kill_switch_tripped"]
    return state["runtime_enabled"] and not state["kill_switch_tripped"]


def _trip_kill_switch(reason: str) -> None:
    if db.trip_binomo_kill_switch(reason):
        logger.critical("BINOMO KILL SWITCH: %s", reason)
        notify_admin(
            f"🛑 <b>BINOMO KILL SWITCH</b>\n{reason}\n"
            "Виконавця зупинено. Перевір рахунок вручну, тоді /binomo_on.",
            parse_mode="HTML",
        )


# ----------------------------------------------------------------------
# Asset map
# ----------------------------------------------------------------------


def load_asset_map() -> dict[str, dict]:
    path = Path(config.BINOMO_ASSET_MAP_PATH)
    if not path.is_absolute():
        path = config.BASE_DIR / path

    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        logger.exception("Could not load Binomo asset map from %s", path)
        return {}

    assets = data.get("assets") or {}
    if not data.get("_meta", {}).get("verified"):
        logger.warning(
            "Binomo asset map (%s) is marked unverified — trades will only be "
            "placed for pairs whose Binomo name has been manually confirmed. "
            "See _meta.how_to_verify in the file.",
            path,
        )
    return assets


# ----------------------------------------------------------------------
# Playwright session
# ----------------------------------------------------------------------


def _storage_state_path() -> Path:
    path = Path(config.BINOMO_STORAGE_STATE_PATH)
    return path if path.is_absolute() else config.BASE_DIR / path


def login_and_save_session() -> None:
    """One-time (or as-needed) manual login helper: opens a VISIBLE browser,
    lets you log in yourself (including any CAPTCHA/2FA), then saves the
    session to BINOMO_STORAGE_STATE_PATH. Run with:
        python binomo_executor.py --login
    """
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()
        page = context.new_page()
        page.goto(BINOMO_BASE_URL)

        print(
            "\nA browser window has opened. Log into your Binomo account "
            "manually (solve any CAPTCHA/2FA yourself — this tool never "
            "attempts that). Once you're logged in and can see your "
            "balance, come back here and press Enter.\n"
        )
        input("Press Enter once logged in... ")

        state_path = _storage_state_path()
        state_path.parent.mkdir(parents=True, exist_ok=True)
        context.storage_state(path=str(state_path))
        print(f"Session saved to {state_path}. You can close the browser now.")
        browser.close()


def _launch_session(playwright, *, headless: bool):
    state_path = _storage_state_path()
    if not state_path.exists():
        raise RuntimeError(
            f"No saved Binomo session at {state_path}. Run "
            "`python binomo_executor.py --login` first."
        )

    browser = playwright.chromium.launch(headless=headless)
    context = browser.new_context(storage_state=str(state_path))
    page = context.new_page()
    page.goto(BINOMO_TRADE_URL)
    return browser, context, page


def _is_logged_in(page) -> bool:
    try:
        page.wait_for_selector(SELECTORS["login_indicator"], timeout=_DEFAULT_FIND_TIMEOUT_MS)
        return True
    except Exception:
        return False


# ----------------------------------------------------------------------
# Safe DOM interaction — never guesses an alternate selector. On timeout:
# screenshot, log, return None. Callers must treat None as "stop, don't
# trade", per the task's own explicit rule.
# ----------------------------------------------------------------------


def _screenshot(page, tag: str) -> Optional[str]:
    try:
        SCREENSHOT_DIR.mkdir(parents=True, exist_ok=True)
        ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
        path = SCREENSHOT_DIR / f"{ts}_{tag}.png"
        page.screenshot(path=str(path))
        return str(path)
    except Exception:
        logger.exception("Could not save audit screenshot for %s", tag)
        return None


def _safe_find(page, selector: str, *, description: str, timeout_ms: int = _DEFAULT_FIND_TIMEOUT_MS):
    try:
        return page.wait_for_selector(selector, timeout=timeout_ms)
    except Exception:
        shot = _screenshot(page, f"missing_{description}")
        logger.error(
            "Binomo executor: element not found for '%s' (selector=%r). "
            "Not guessing an alternative — stopping this action. Screenshot: %s",
            description, selector, shot,
        )
        notify_admin(
            f"⚠️ Binomo executor: елемент \"{description}\" не знайдено на сторінці. "
            "Потрібна ручна перевірка (можливо, змінився дизайн сайту). "
            f"Скріншот: {shot or 'не вдалося зберегти'}",
        )
        return None


# ----------------------------------------------------------------------
# Balance
# ----------------------------------------------------------------------


def get_account_balance(page) -> Optional[float]:
    el = _safe_find(page, SELECTORS["balance_amount"], description="balance_amount")
    if el is None:
        return None

    try:
        text = el.inner_text().strip()
        cleaned = "".join(ch for ch in text if ch.isdigit() or ch in ".,").replace(",", "")
        return float(cleaned) if cleaned else None
    except Exception:
        logger.exception("Could not parse Binomo balance text")
        return None


# ----------------------------------------------------------------------
# Trade placement
# ----------------------------------------------------------------------


def place_binary_trade(page, asset: str, direction: str, amount: float, expiry_seconds: int) -> dict:
    """direction: 'up' | 'down'. Returns {"success": bool, "error": str|None}.
    Every real click on amount/direction is preceded by an audit screenshot,
    per the task's audit-trail requirement."""
    if direction not in ("up", "down"):
        return {"success": False, "error": f"invalid direction: {direction}"}

    search_input = _safe_find(page, SELECTORS["asset_search_input"], description="asset_search_input")
    if search_input is None:
        return {"success": False, "error": "asset_search_input not found"}
    search_input.fill(asset)

    asset_option = _safe_find(page, f"{SELECTORS['asset_option']}:has-text('{asset}')", description="asset_option")
    if asset_option is None:
        return {"success": False, "error": f"asset option not found for {asset!r}"}
    asset_option.click()

    expiry_dropdown = _safe_find(page, SELECTORS["expiry_selector"], description="expiry_selector")
    if expiry_dropdown is None:
        return {"success": False, "error": "expiry_selector not found"}
    expiry_dropdown.click()

    expiry_option = _safe_find(
        page, f"{SELECTORS['expiry_option']}:has-text('{expiry_seconds}')", description="expiry_option"
    )
    if expiry_option is None:
        return {"success": False, "error": f"expiry option not found for {expiry_seconds}s"}
    expiry_option.click()

    amount_input = _safe_find(page, SELECTORS["amount_input"], description="amount_input")
    if amount_input is None:
        return {"success": False, "error": "amount_input not found"}

    _screenshot(page, f"before_amount_{asset}_{direction}")
    amount_input.fill(f"{amount:.2f}")

    direction_selector = SELECTORS["up_button"] if direction == "up" else SELECTORS["down_button"]
    direction_button = _safe_find(page, direction_selector, description=f"{direction}_button")
    if direction_button is None:
        return {"success": False, "error": f"{direction}_button not found"}

    _screenshot(page, f"before_click_{asset}_{direction}")
    direction_button.click()

    confirmation = _safe_find(
        page, SELECTORS["trade_confirmation_toast"], description="trade_confirmation_toast", timeout_ms=5000
    )
    if confirmation is None:
        # Not necessarily a failure — some UIs skip a toast — but we can't
        # positively confirm the trade went through either. Log loudly.
        logger.warning("Binomo executor: no confirmation toast seen after clicking %s on %s", direction, asset)

    return {"success": True, "error": None}


def read_trade_result(page, asset: str, entered_after: datetime) -> dict:
    """Reads the most recent resolved trade for `asset` opened at/after
    `entered_after` from Binomo's trade history. Returns
    {"result": "win"|"loss"|"unknown", "payout_amount": float|None}."""
    history_tab = _safe_find(page, SELECTORS["trade_history_tab"], description="trade_history_tab")
    if history_tab is None:
        return {"result": "unknown", "payout_amount": None}
    history_tab.click()

    row = _safe_find(page, f"{SELECTORS['trade_history_row']}:has-text('{asset}')", description="trade_history_row")
    if row is None:
        return {"result": "unknown", "payout_amount": None}

    try:
        text = row.inner_text().lower()
        if "win" in text or "виграш" in text:
            outcome = "win"
        elif "loss" in text or "програш" in text:
            outcome = "loss"
        else:
            outcome = "unknown"

        digits = "".join(ch for ch in text if ch.isdigit() or ch in ".,-").strip()
        payout = float(digits.replace(",", "")) if digits else None
        return {"result": outcome, "payout_amount": payout}
    except Exception:
        logger.exception("Could not parse Binomo trade history row for %s", asset)
        return {"result": "unknown", "payout_amount": None}


# ----------------------------------------------------------------------
# Risk checks
# ----------------------------------------------------------------------


def _check_risk_limits(balance: float) -> Optional[str]:
    """Returns a reason string if a trade should be blocked, else None.
    Trips the kill switch itself when a hard limit (consecutive losses /
    daily loss) is breached."""
    trades_today = db.count_binomo_trades_today(config.BINOMO_ACCOUNT_MODE)
    if trades_today >= config.BINOMO_MAX_TRADES_PER_DAY:
        return f"MAX_TRADES_PER_DAY reached ({trades_today}/{config.BINOMO_MAX_TRADES_PER_DAY})"

    losses = db.get_consecutive_binomo_losses(config.BINOMO_ACCOUNT_MODE)
    if losses >= config.BINOMO_MAX_CONSECUTIVE_LOSSES:
        _trip_kill_switch(
            f"{losses} збитків поспіль (ліміт {config.BINOMO_MAX_CONSECUTIVE_LOSSES})"
        )
        return "MAX_CONSECUTIVE_LOSSES kill switch tripped"

    daily_pnl = db.get_daily_binomo_pnl(config.BINOMO_ACCOUNT_MODE)
    max_daily_loss = balance * (config.BINOMO_MAX_DAILY_LOSS_PERCENT / 100.0)
    if daily_pnl <= -max_daily_loss:
        _trip_kill_switch(
            f"Денний PnL {daily_pnl:.2f} перевищив ліміт -{max_daily_loss:.2f} "
            f"({config.BINOMO_MAX_DAILY_LOSS_PERCENT}% балансу)"
        )
        return "MAX_DAILY_LOSS_PERCENT kill switch tripped"

    return None


# ----------------------------------------------------------------------
# Signal stream (background thread — only ever pushes into a queue; all
# Playwright calls stay on the main thread, since a Page isn't safe to
# drive from multiple threads at once)
# ----------------------------------------------------------------------


def _signal_stream_url() -> str:
    base = config.get_public_base_url()
    token = config.get_admin_access_token()
    if not token:
        raise RuntimeError(
            "ADMIN_ACCESS_TOKEN is not set — the local executor needs it to "
            "read /api/signal-stream from the cloud instance."
        )
    return f"{base}/api/signal-stream?admin_token={token}"


def _stream_signals(out_queue: "queue.Queue[dict]", stop_event: threading.Event) -> None:
    import sseclient

    url = _signal_stream_url()
    while not stop_event.is_set():
        try:
            response = requests.get(url, stream=True, timeout=(10, None))
            client = sseclient.SSEClient(response)
            for event in client.events():
                if stop_event.is_set():
                    break
                if not event.data:
                    continue
                try:
                    payload = json.loads(event.data)
                except ValueError:
                    continue
                if payload.get("_ping"):
                    continue
                out_queue.put(payload)
        except Exception:
            logger.warning("Binomo executor: signal stream disconnected, retrying in 10s", exc_info=True)
            time.sleep(10)


# ----------------------------------------------------------------------
# Main loop
# ----------------------------------------------------------------------


def _handle_signal(page, asset_map: dict, signal: dict) -> None:
    if not is_active():
        return

    verdict = str(signal.get("verdict_text") or "").upper()
    if verdict not in ("BUY", "SELL"):
        return

    pair = str(signal.get("pair") or "").upper()
    entry = asset_map.get(pair)
    if not entry or not entry.get("binomo_name"):
        logger.debug("Binomo executor: %s not in asset map, skipping", pair)
        return

    balance = get_account_balance(page)
    if not balance or balance <= 0:
        logger.warning("Binomo executor: could not read balance, skipping %s", pair)
        return

    block_reason = _check_risk_limits(balance)
    if block_reason:
        logger.info("Binomo executor: blocked %s (%s)", pair, block_reason)
        return

    direction = "up" if verdict == "BUY" else "down"
    expiry_seconds = signal_tracking.compute_horizon_seconds(signal.get("timeframe"))
    amount = round(balance * (config.BINOMO_STAKE_PERCENT / 100.0), 2)
    asset_name = entry["binomo_name"]

    trade_id = db.create_binomo_trade(
        asset=asset_name,
        pair=pair,
        direction=direction,
        amount=amount,
        expiry_seconds=expiry_seconds,
        account_mode=config.BINOMO_ACCOUNT_MODE,
    )
    if not trade_id:
        logger.error("Binomo executor: could not log pending trade for %s, aborting placement", pair)
        return

    logger.info(
        "BINOMO: placing #%s %s %s amount=%.2f expiry=%ss (mode=%s)",
        trade_id, asset_name, direction, amount, expiry_seconds, config.BINOMO_ACCOUNT_MODE,
    )
    result = place_binary_trade(page, asset_name, direction, amount, expiry_seconds)

    if not result["success"]:
        db.mark_binomo_trade_error(trade_id, result["error"] or "unknown error")
        notify_admin(f"❌ Binomo #{trade_id} {asset_name} {direction}: {result['error']}")
        return

    notify_admin(
        f"📥 Binomo #{trade_id} {asset_name} {direction.upper()}\n"
        f"Сума: {amount:.2f} · Експірація: {expiry_seconds}с · Режим: {config.BINOMO_ACCOUNT_MODE}"
    )


def _resolve_due_trades(page) -> None:
    now = datetime.now(timezone.utc).replace(tzinfo=None)

    for trade in db.get_pending_binomo_trades(config.BINOMO_ACCOUNT_MODE):
        entry_ts = trade["entry_ts"]
        if not isinstance(entry_ts, datetime):
            continue
        due_at = entry_ts.timestamp() + trade["expiry_seconds"]
        if now.timestamp() < due_at:
            continue

        outcome = read_trade_result(page, trade["asset"], entry_ts)
        if outcome["result"] == "unknown":
            continue  # try again next pass; don't guess

        if db.resolve_binomo_trade(trade["id"], result=outcome["result"], payout_amount=outcome["payout_amount"]):
            payout = outcome["payout_amount"]
            logger.info(
                "BINOMO: #%s %s %s -> %s (payout=%s)",
                trade["id"], trade["asset"], trade["direction"], outcome["result"], payout,
            )
            notify_admin(
                f"📤 Binomo #{trade['id']} {trade['asset']} {trade['direction'].upper()} "
                f"→ {outcome['result'].upper()}"
                + (f" ({payout:+.2f})" if isinstance(payout, (int, float)) else "")
            )


def run(*, headless: bool = None) -> None:
    from playwright.sync_api import sync_playwright

    if not config.BINOMO_EXECUTOR_ENABLED:
        logger.warning("BINOMO_EXECUTOR_ENABLED=false — exiting immediately. Set it in your local .env to run.")
        return

    asset_map = load_asset_map()
    if not asset_map:
        logger.error("Binomo asset map is empty — nothing to trade. Check %s", config.BINOMO_ASSET_MAP_PATH)
        return

    signal_queue: "queue.Queue[dict]" = queue.Queue()
    stop_event = threading.Event()
    stream_thread = threading.Thread(
        target=_stream_signals, args=(signal_queue, stop_event), name="binomo-signal-stream", daemon=True
    )
    stream_thread.start()

    with sync_playwright() as p:
        browser, context, page = _launch_session(p, headless=config.BINOMO_HEADLESS if headless is None else headless)

        if not _is_logged_in(page):
            notify_admin(
                "🛑 Binomo executor: сесія недійсна/протермінована. "
                "Запусти `python binomo_executor.py --login` вручну на ноуті."
            )
            logger.critical("Binomo executor: not logged in (stale storage_state?). Exiting.")
            browser.close()
            stop_event.set()
            return

        logger.info("Binomo executor started (mode=%s, enabled=%s)", config.BINOMO_ACCOUNT_MODE, config.BINOMO_EXECUTOR_ENABLED)

        try:
            while True:
                try:
                    signal = signal_queue.get(timeout=2.0)
                    _handle_signal(page, asset_map, signal)
                except queue.Empty:
                    pass

                _resolve_due_trades(page)
        except KeyboardInterrupt:
            logger.info("Binomo executor stopping (KeyboardInterrupt).")
        finally:
            stop_event.set()
            browser.close()


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")

    parser = argparse.ArgumentParser(description="Binomo binary-option executor (local, Playwright-based).")
    parser.add_argument("--login", action="store_true", help="One-time/manual login helper; saves storage_state.json.")
    parser.add_argument("--run", action="store_true", help="Run the live executor loop.")
    parser.add_argument("--headless", action="store_true", help="Force headless mode for --run.")
    args = parser.parse_args()

    if args.login:
        login_and_save_session()
    elif args.run:
        run(headless=True if args.headless else None)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
