# docker-compose.yml
version: "3.9"

services:
  app:
    build: .
    command: python app.py
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    restart: unless-stopped