# docker-compose.yml
version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: zigzag-redis
    ports:
      - "6379:6379"

  streamer:
    build: .
    command: python price_streamer.py
    environment:
      # Важливо: створіть файл .env поруч з цим файлом
      # і додайте туди ваші секретні змінні, напр. CT_CLIENT_ID=...
      - REDIS_URL=redis://redis:6379/0
      - CT_CLIENT_ID=${CT_CLIENT_ID}
      - CT_CLIENT_SECRET=${CT_CLIENT_SECRET}
      - CTRADER_ACCESS_TOKEN=${CTRADER_ACCESS_TOKEN}
      - DEMO_ACCOUNT_ID=${DEMO_ACCOUNT_ID}
      - FLY_APP_NAME: ${FLY_APP_NAME}
    depends_on:
      - redis
    restart: unless-stopped

  api:
    build: .
    command: python app.py
    environment:
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CT_CLIENT_ID=${CT_CLIENT_ID}
      - CT_CLIENT_SECRET=${CT_CLIENT_SECRET}
      - CTRADER_ACCESS_TOKEN=${CTRADER_ACCESS_TOKEN}
      - DEMO_ACCOUNT_ID=${DEMO_ACCOUNT_ID}
      - FLY_APP_NAME=${FLY_APP_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - streamer
    restart: unless-stopped