# fly.toml

app = "zigzag-bot-package"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION = "python"
  
# Оскільки наш додаток - це бот (фоновий процес), а не веб-сервер,
# ми не використовуємо секцію [[http_service]].
# Замість неї ми прямо вказуємо команду для запуску.
[processes]
  app = "python main.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[experimental]
  auto_rollback = true