# fly.toml
app = "zigzag-bot-package"
primary_region = "ams" # Повертаємо Амстердам

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PORT = "8080"

[build]
dockerfile = "Dockerfile"

[deploy]
# Повертаємо таймаут 10 хвилин
release_command = "python app.py"
release_command_timeout = "600s"

[mounts]
source="signals_data"
destination="/data"

# [http_service] секцію видалено, щоб уникнути Health Checks

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512