# fly.toml
app = "zigzag-bot-package"

[build]
  dockerfile = "Dockerfile"

[env]
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION = "python"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.http_checks]]
    path = "/health"
    interval = "30s"
    timeout = "10s"
    grace_period = "30s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512