# netlify.toml

[build]
  publish = "webapp"
  command = "echo 'No build step required'"

[[headers]]
  for = "/*"
  [headers.values]
    # Додаємо 'unsafe-eval', щоб дозволити роботу Plotly.js
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.plot.ly https://telegram.org; connect-src 'self' https://zigzag-bot-package.fly.dev;"