# Налаштування збірки: вказуємо, яку папку публікувати
[build]
  publish = "webapp"
  command = "echo 'No build step required'"

# Налаштування заголовків: вирішуємо проблему з Content Security Policy
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.plot.ly https://telegram.org;"