# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiPayloadType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18OpenApiPayloadType.proto*\xac\x06\n\x14ProtoOAPayloadType\x12\x1d\n\x19PROTO_OA_APPLICATION_AUTH\x10\xea\x07\x12\x1a\n\x16PROTO_OA_ACCOUNT_AUTH\x10\xeb\x07\x12\x14\n\x10PROTO_OA_VERSION\x10\xec\x07\x12\x1d\n\x19PROTO_OA_NEW_ORDER_SINGLE\x10\xed\x07\x12\x18\n\x14PROTO_OA_CANCEL_ORDER\x10\xee\x07\x12\x17\n\x13PROTO_OA_CLOSE_POSITION\x10\xef\x07\x12\x18\n\x14PROTO_OA_AMEND_POSITION\x10\xf0\x07\x12\x15\n\x11PROTO_OA_AMEND_ORDER\x10\xf1\x07\x12\x1b\n\x17PROTO_OA_DEAL_LIST_BY_ID\x10\xf2\x07\x12\x1b\n\x17PROTO_OA_DEAL_LIST_BY_POSITION_ID\x10\xf3\x07\x12\x15\n\x11PROTO_OA_GET_DEALS\x10\xf4\x07\x12\x1a\n\x16PROTO_OA_GET_POSITIONS\x10\xf5\x07\x12\x18\n\x14PROTO_OA_GET_ORDERS\x10\xf6\x07\x12\x1a\n\x16PROTO_OA_GET_TRENDBARS\x10\xf7\x07\x12\x16\n\x12PROTO_OA_GET_PROFILE\x10\xf8\x07\x12\x17\n\x13PROTO_OA_GET_TICKDATA\x10\xf9\x07\x12\x18\n\x14PROTO_OA_ACCOUNTS_TOKEN_INVALIDATED\x10\xfa\x07\x12\x15\n\x11PROTO_OA_CLIENT_DISCONNECT\x10\xfb\x07\x12\x1b\n\x17PROTO_OA_GET_ACCOUNT_LIST_BY_ACCESS_TOKEN\x10\xfc\x07\x12\x1a\n\x16PROTO_OA_GET_SYMBOLS_LIST\x10\xfd\x07\x12\x17\n\x13PROTO_OA_SUBSCRIBE_SPOTS\x10\xfe\x07\x12\x19\n\x15PROTO_OA_UNSUBSCRIBE_SPOTS\x10\xff\x07\x12\x14\n\x10PROTO_OA_SPOT_EVENT\x10\x80\x08\x12\x16\n\x12PROTO_OA_EXECUTION\x10\x81\x08\x12\x1a\n\x16PROTO_OA_SUBSCRIBE_DEPTH_QUOTES\x10\x82\x08\x12\x1c\n\x18PROTO_OA_UNSUBSCRIBE_DEPTH_QUOTES\x10\x83\x08\x12\x16\n\x12PROTO_OA_DEPTH_EVENT\x10\x84\x08\x12\x18\n\x14PROTO_OA_SYMBOL_BY_ID\x10\x85\x08\x12 \n\x1cPROTO_OA_GET_SYMBOLS_FOR_CONVERSION\x10\x86\x08\x62\x06proto3')
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OpenApiPayloadType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTOOAPAYLOADTYPE._serialized_start = 29
  _PROTOOAPAYLOADTYPE._serialized_end = 837
# @@protoc_insertion_point(module_scope)