# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiCommonMessages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='OpenApiCommonMessages.proto',
  package='com.xtrader.protocol.openapi.v2',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bOpenApiCommonMessages.proto\x12\x1f\x63om.xtrader.protocol.openapi.v2\"\"\n\rProtoErrorRes\x12\x11\n\terrorCode\x18\x01 \x01(\t\" \n\x0eProtoHeartbeat\x12\x0e\n\x06millis\x18\x01 \x01(\x04\"G\n\x0cProtoMessage\x12\x33\n\x0bpayloadType\x18\x01 \x01(\x0e\x32\x1e.com.xtrader.protocol.openapi.v2.ProtoOAPayloadType\x12\x0f\n\x07payload\x18\x02 \x01(\x0c*\xf2\x01\n\x12ProtoOAPayloadType\x12\x1c\n\x18PROTO_OA_ERROR_RESPONSE\x10\x00\x12\x1a\n\x16PROTO_OA_HEARTBEAT_MSG\x10\x01\x12\"\n\x1ePROTO_OA_APPLICATION_AUTH_REQ\x10\xe4\x11\x12#\n\x1fPROTO_OA_APPLICATION_AUTH_RES\x10\xe5\x11\x12\x1f\n\x1bPROTO_OA_ACCOUNT_AUTH_REQ\x10\xe6\x11\x12 \n\x1cPROTO_OA_ACCOUNT_AUTH_RES\x10\xe7\x11\x12*\n&PROTO_OA_SUBSCRIBE_LIVE_TRENDBAR_REQ\x10\xec\x11\x12\x1f\n\x1bPROTO_OA_TRENDBAR_EVENT\x10\xf2\x11\x62\x06proto3'
)

_PROTOOAPAYLOADTYPE = _descriptor.EnumDescriptor(
  name='ProtoOAPayloadType',
  full_name='com.xtrader.protocol.openapi.v2.ProtoOAPayloadType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROTO_OA_ERROR_RESPONSE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTO_OA_HEARTBEAT_MSG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTO_OA_APPLICATION_AUTH_REQ', index=2, number=2276,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTO_OA_APPLICATION_AUTH_RES', index=3, number=2277,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTO_OA_ACCOUNT_AUTH_REQ', index=4, number=2278,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTO_OA_ACCOUNT_AUTH_RES', index=5, number=2279,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTO_OA_SUBSCRIBE_LIVE_TRENDBAR_REQ', index=6, number=2284,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTO_OA_TRENDBAR_EVENT', index=7, number=2290,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=208,
  serialized_end=450,
)
_sym_db.RegisterEnumDescriptor(_PROTOOAPAYLOADTYPE)

ProtoOAPayloadType = enum_type_wrapper.EnumTypeWrapper(_PROTOOAPAYLOADTYPE)
PROTO_OA_ERROR_RESPONSE = 0
PROTO_OA_HEARTBEAT_MSG = 1
PROTO_OA_APPLICATION_AUTH_REQ = 2276
PROTO_OA_APPLICATION_AUTH_RES = 2277
PROTO_OA_ACCOUNT_AUTH_REQ = 2278
PROTO_OA_ACCOUNT_AUTH_RES = 2279
PROTO_OA_SUBSCRIBE_LIVE_TRENDBAR_REQ = 2284
PROTO_OA_TRENDBAR_EVENT = 2290

ProtoErrorRes = _reflection.GeneratedProtocolMessageType('ProtoErrorRes', (_message.Message,), {
  'DESCRIPTOR' : _descriptor.Descriptor(
    name='ProtoErrorRes',
    full_name='com.xtrader.protocol.openapi.v2.ProtoErrorRes',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
      _descriptor.FieldDescriptor(
        name='errorCode', full_name='com.xtrader.protocol.openapi.v2.ProtoErrorRes.errorCode', index=0,
        number=1, type=9, cpp_type=9, label=1,
        has_default_value=False, default_value=b"".decode('utf-8'),
        message_type=None, enum_type=None, containing_type=None,
        is_extension=False, extension_scope=None,
        serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=64,
    serialized_end=98,
  ),
  '__module__' : 'OpenApiCommonMessages_pb2'
})
_sym_db.RegisterMessage(ProtoErrorRes)

ProtoHeartbeat = _reflection.GeneratedProtocolMessageType('ProtoHeartbeat', (_message.Message,), {
  'DESCRIPTOR' : _descriptor.Descriptor(
    name='ProtoHeartbeat',
    full_name='com.xtrader.protocol.openapi.v2.ProtoHeartbeat',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
      _descriptor.FieldDescriptor(
        name='millis', full_name='com.xtrader.protocol.openapi.v2.ProtoHeartbeat.millis', index=0,
        number=1, type=4, cpp_type=4, label=1,
        has_default_value=False, default_value=0,
        message_type=None, enum_type=None, containing_type=None,
        is_extension=False, extension_scope=None,
        serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=100,
    serialized_end=132,
  ),
  '__module__' : 'OpenApiCommonMessages_pb2'
})
_sym_db.RegisterMessage(ProtoHeartbeat)

ProtoMessage = _reflection.GeneratedProtocolMessageType('ProtoMessage', (_message.Message,), {
  'DESCRIPTOR' : _descriptor.Descriptor(
    name='ProtoMessage',
    full_name='com.xtrader.protocol.openapi.v2.ProtoMessage',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
      _descriptor.FieldDescriptor(
        name='payloadType', full_name='com.xtrader.protocol.openapi.v2.ProtoMessage.payloadType', index=0,
        number=1, type=14, cpp_type=8, label=1,
        has_default_value=False, default_value=0,
        message_type=None, enum_type=None, containing_type=None,
        is_extension=False, extension_scope=None,
        serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
      _descriptor.FieldDescriptor(
        name='payload', full_name='com.xtrader.protocol.openapi.v2.ProtoMessage.payload', index=1,
        number=2, type=12, cpp_type=9, label=1,
        has_default_value=False, default_value=b"",
        message_type=None, enum_type=None, containing_type=None,
        is_extension=False, extension_scope=None,
        serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=134,
    serialized_end=205,
  ),
  '__module__' : 'OpenApiCommonMessages_pb2'
})
_sym_db.RegisterMessage(ProtoMessage)
_PROTOMESSAGE.fields_by_name['payloadType'].enum_type = _PROTOOAPAYLOADTYPE