# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiCommonModelMessages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='OpenApiCommonModelMessages.proto',
  package='com.xtrader.protocol.openapi.v2',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n OpenApiCommonModelMessages.proto\x12\x1f\x63om.xtrader.protocol.openapi.v2\"v\n\rProtoOATrendbar\x12\x0e\n\x06volume\x18\x03 \x01(\x03\x12\x0c\n\x04open\x18\x04 \x01(\x04\x12\r\n\x05\x63lose\x18\x05 \x01(\x04\x12\x0c\n\x04high\x18\x06 \x01(\x04\x12\x0b\n\x03low\x18\x07 \x01(\x04\x12\x1d\n\x15utcTimestampInMinutes\x18\x08 \x01(\r*\xb3\x01\n\x16ProtoOATrendbarPeriod\x12\x08\n\x04MIN1\x10\x01\x12\x08\n\x04MIN2\x10\x02\x12\x08\n\x04MIN3\x10\x03\x12\x08\n\x04MIN4\x10\x04\x12\x08\n\x04MIN5\x10\x05\x12\t\n\x05MIN10\x10\x06\x12\t\n\x05MIN15\x10\x07\x12\t\n\x05MIN30\x10\x08\x12\x08\n\x04HOUR\x10\t\x12\n\n\x06HOUR4\x10\n\x12\n\n\x06HOUR12\x10\x0b\x12\x07\n\x03\x44\x41Y\x10\x0c\x12\x08\n\x04WEEK\x10\r\x12\t\n\x05MONTH\x10\x0e\x62\x06proto3'
)

_PROTOOATRENDBARPERIOD = _descriptor.EnumDescriptor(
  name='ProtoOATrendbarPeriod',
  full_name='com.xtrader.protocol.openapi.v2.ProtoOATrendbarPeriod',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(name='MIN1', index=0, number=1, serialized_options=None, type=None, create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(name='MIN2', index=1, number=2, serialized_options=None, type=None, create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(name='MIN3', index=2, number=3, serialized_options=None, type=None, create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(name='MIN4', index=3, number=4, serialized_options=None, type=None, create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(name='MIN5', index=4, number=5, serialized_options=None, type=None, create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(name='MIN10', index=5, number=6, serialized_options=None, type=None, create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(name='MIN15', index=6, number=7, serialized_options=None, type=None, create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(name='MIN30', index=7, number=8, serialized_options=None, type=None, create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(name='HOUR', index=8, number=9, serialized_options=None, type=None, create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(name='HOUR4', index=9, number=10, serialized_options=None, type=None, create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(name='HOUR12', index=10, number=11, serialized_options=None, type=None, create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(name='DAY', index=11, number=12, serialized_options=None, type=None, create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(name='WEEK', index=12, number=13, serialized_options=None, type=None, create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(name='MONTH', index=13, number=14, serialized_options=None, type=None, create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=186,
  serialized_end=365,
)
_sym_db.RegisterEnumDescriptor(_PROTOOATRENDBARPERIOD)

ProtoOATrendbarPeriod = enum_type_wrapper.EnumTypeWrapper(_PROTOOATRENDBARPERIOD)
MIN1 = 1; MIN2 = 2; MIN3 = 3; MIN4 = 4; MIN5 = 5; MIN10 = 6; MIN15 = 7; MIN30 = 8; HOUR = 9; HOUR4 = 10; HOUR12 = 11; DAY = 12; WEEK = 13; MONTH = 14

ProtoOATrendbar = _reflection.GeneratedProtocolMessageType('ProtoOATrendbar', (_message.Message,), {
  'DESCRIPTOR' : _descriptor.Descriptor(
    name='ProtoOATrendbar',
    full_name='com.xtrader.protocol.openapi.v2.ProtoOATrendbar',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
      _descriptor.FieldDescriptor(name='volume', full_name='com.xtrader.protocol.openapi.v2.ProtoOATrendbar.volume', index=0, number=3, type=3, cpp_type=2, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
      _descriptor.FieldDescriptor(name='open', full_name='com.xtrader.protocol.openapi.v2.ProtoOATrendbar.open', index=1, number=4, type=4, cpp_type=4, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
      _descriptor.FieldDescriptor(name='close', full_name='com.xtrader.protocol.openapi.v2.ProtoOATrendbar.close', index=2, number=5, type=4, cpp_type=4, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
      _descriptor.FieldDescriptor(name='high', full_name='com.xtrader.protocol.openapi.v2.ProtoOATrendbar.high', index=3, number=6, type=4, cpp_type=4, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
      _descriptor.FieldDescriptor(name='low', full_name='com.xtrader.protocol.openapi.v2.ProtoOATrendbar.low', index=4, number=7, type=4, cpp_type=4, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
      _descriptor.FieldDescriptor(name='utcTimestampInMinutes', full_name='com.xtrader.protocol.openapi.v2.ProtoOATrendbar.utcTimestampInMinutes', index=5, number=8, type=13, cpp_type=3, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=66, serialized_end=184),
  '__module__' : 'OpenApiCommonModelMessages_pb2'
})
_sym_db.RegisterMessage(ProtoOATrendbar)