# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from . import OpenApiCommonModelMessages_pb2 as OpenApiCommonModelMessages__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='OpenApiModelMessages.proto',
  package='com.xtrader.protocol.openapi.v2',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aOpenApiModelMessages.proto\x12\x1f\x63om.xtrader.protocol.openapi.v2\x1a OpenApiCommonModelMessages.proto\"H\n\x1bProtoOAApplicationAuthReq\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x17\n\x0f\x63lientSecret\x18\x02 \x01(\t\" \n\x1cProtoOAApplicationAuthRes\"G\n\x17ProtoOAAccountAuthReq\x12\x1b\n\x13\x63tidTraderAccountId\x18\x01 \x01(\x03\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x02 \x01(\t\"\x1a\n\x18ProtoOAAccountAuthRes\"\xad\x01\n\"ProtoOASubscribeLiveTrendbarReq\x12\x1b\n\x13\x63tidTraderAccountId\x18\x01 \x01(\x03\x12\x10\n\x08symbolId\x18\x02 \x01(\x03\x12R\n\ttimeframe\x18\x03 \x01(\x0e\x32?.com.xtrader.protocol.openapi.v2.ProtoOATrendbarPeriod\"$\n#ProtoOASubscribeLiveTrendbarRes\"i\n\x14ProtoOATrendbarEvent\x12\x1b\n\x13\x63tidTraderAccountId\x18\x01 \x01(\x03\x12\x10\n\x08symbolId\x18\x02 \x01(\x03\x12\"\n\x08trendbar\x18\x03 \x03(\x0b\x32\x10.ProtoOATrendbarb\x06proto3'
)

ProtoOAApplicationAuthReq = _reflection.GeneratedProtocolMessageType('ProtoOAApplicationAuthReq', (_message.Message,), {
  'DESCRIPTOR' : _descriptor.Descriptor(
    name='ProtoOAApplicationAuthReq',
    full_name='com.xtrader.protocol.openapi.v2.ProtoOAApplicationAuthReq',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
      _descriptor.FieldDescriptor(name='clientId', full_name='com.xtrader.protocol.openapi.v2.ProtoOAApplicationAuthReq.clientId', index=0, number=1, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b"".decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
      _descriptor.FieldDescriptor(name='clientSecret', full_name='com.xtrader.protocol.openapi.v2.ProtoOAApplicationAuthReq.clientSecret', index=1, number=2, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b"".decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=97, serialized_end=169),
  '__module__' : 'OpenApiModelMessages_pb2'
})
_sym_db.RegisterMessage(ProtoOAApplicationAuthReq)

ProtoOAApplicationAuthRes = _reflection.GeneratedProtocolMessageType('ProtoOAApplicationAuthRes', (_message.Message,), {
  'DESCRIPTOR' : _descriptor.Descriptor(name='ProtoOAApplicationAuthRes', full_name='com.xtrader.protocol.openapi.v2.ProtoOAApplicationAuthRes', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=171, serialized_end=203),
  '__module__' : 'OpenApiModelMessages_pb2'
})
_sym_db.RegisterMessage(ProtoOAApplicationAuthRes)

ProtoOAAccountAuthReq = _reflection.GeneratedProtocolMessageType('ProtoOAAccountAuthReq', (_message.Message,), {
  'DESCRIPTOR' : _descriptor.Descriptor(
    name='ProtoOAAccountAuthReq',
    full_name='com.xtrader.protocol.openapi.v2.ProtoOAAccountAuthReq',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
      _descriptor.FieldDescriptor(name='ctidTraderAccountId', full_name='com.xtrader.protocol.openapi.v2.ProtoOAAccountAuthReq.ctidTraderAccountId', index=0, number=1, type=3, cpp_type=2, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
      _descriptor.FieldDescriptor(name='accessToken', full_name='com.xtrader.protocol.openapi.v2.ProtoOAAccountAuthReq.accessToken', index=1, number=2, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b"".decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=205, serialized_end=276),
  '__module__' : 'OpenApiModelMessages_pb2'
})
_sym_db.RegisterMessage(ProtoOAAccountAuthReq)

ProtoOAAccountAuthRes = _reflection.GeneratedProtocolMessageType('ProtoOAAccountAuthRes', (_message.Message,), {
  'DESCRIPTOR' : _descriptor.Descriptor(name='ProtoOAAccountAuthRes', full_name='com.xtrader.protocol.openapi.v2.ProtoOAAccountAuthRes', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=278, serialized_end=304),
  '__module__' : 'OpenApiModelMessages_pb2'
})
_sym_db.RegisterMessage(ProtoOAAccountAuthRes)

ProtoOASubscribeLiveTrendbarReq = _reflection.GeneratedProtocolMessageType('ProtoOASubscribeLiveTrendbarReq', (_message.Message,), {
  'DESCRIPTOR' : _descriptor.Descriptor(
    name='ProtoOASubscribeLiveTrendbarReq',
    full_name='com.xtrader.protocol.openapi.v2.ProtoOASubscribeLiveTrendbarReq',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
      _descriptor.FieldDescriptor(name='ctidTraderAccountId', full_name='com.xtrader.protocol.openapi.v2.ProtoOASubscribeLiveTrendbarReq.ctidTraderAccountId', index=0, number=1, type=3, cpp_type=2, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
      _descriptor.FieldDescriptor(name='symbolId', full_name='com.xtrader.protocol.openapi.v2.ProtoOASubscribeLiveTrendbarReq.symbolId', index=1, number=2, type=3, cpp_type=2, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
      _descriptor.FieldDescriptor(name='timeframe', full_name='com.xtrader.protocol.openapi.v2.ProtoOASubscribeLiveTrendbarReq.timeframe', index=2, number=3, type=14, cpp_type=8, label=1, has_default_value=False, default_value=1, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=307, serialized_end=480),
  '__module__' : 'OpenApiModelMessages_pb2'
})
_sym_db.RegisterMessage(ProtoOASubscribeLiveTrendbarReq)
_PROTOOASUBSCRIBELIVETRENDBARREQ.fields_by_name['timeframe'].enum_type = OpenApiCommonModelMessages__pb2._PROTOOATRENDBARPERIOD

ProtoOASubscribeLiveTrendbarRes = _reflection.GeneratedProtocolMessageType('ProtoOASubscribeLiveTrendbarRes', (_message.Message,), {
  'DESCRIPTOR' : _descriptor.Descriptor(name='ProtoOASubscribeLiveTrendbarRes', full_name='com.xtrader.protocol.openapi.v2.ProtoOASubscribeLiveTrendbarRes', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=482, serialized_end=518),
  '__module__' : 'OpenApiModelMessages_pb2'
})
_sym_db.RegisterMessage(ProtoOASubscribeLiveTrendbarRes)

ProtoOATrendbarEvent = _reflection.GeneratedProtocolMessageType('ProtoOATrendbarEvent', (_message.Message,), {
  'DESCRIPTOR' : _descriptor.Descriptor(
    name='ProtoOATrendbarEvent',
    full_name='com.xtrader.protocol.openapi.v2.ProtoOATrendbarEvent',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
      _descriptor.FieldDescriptor(name='ctidTraderAccountId', full_name='com.xtrader.protocol.openapi.v2.ProtoOATrendbarEvent.ctidTraderAccountId', index=0, number=1, type=3, cpp_type=2, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
      _descriptor.FieldDescriptor(name='symbolId', full_name='com.xtrader.protocol.openapi.v2.ProtoOATrendbarEvent.symbolId', index=1, number=2, type=3, cpp_type=2, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
      _descriptor.FieldDescriptor(name='trendbar', full_name='com.xtrader.protocol.openapi.v2.ProtoOATrendbarEvent.trendbar', index=2, number=3, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=520, serialized_end=625),
  '__module__' : 'OpenApiModelMessages_pb2'
})
_sym_db.RegisterMessage(ProtoOATrendbarEvent)
_PROTOOATRENDBAREVENT.fields_by_name['trendbar'].message_type = OpenApiCommonModelMessages__pb2._PROTOOATRENDBAR