name: Fly Deploy

on:
  push:
    branches:
      - main # Або master, залежно від назви вашої основної гілки

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-action@master # <-- Ось тут виправлення, я додав @master
        with:
          args: "deploy"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}